// Auto-generated — do not edit manually
// Run: node scripts/generate_audio.js
const audioMap = {
  "Imagine this... The lunch lady is arranging muffins on a tray.": "/assets/audio/thinking_imagine_this_the_lunch_lady_is_arranging_muffins_on_a_tray.mp3",
  "She places them in neat rows and columns.": "/assets/audio/statement_she_places_them_in_neat_rows_and_columns.mp3",
  "She put 3 rows of muffins, with 4 muffins in each row.": "/assets/audio/question_she_put_3_rows_of_muffins_with_4_muffins_in_each_row.mp3",
  "Can you figure out how many muffins there are in all — without counting one by one?": "/assets/audio/question_can_you_figure_out_how_many_muffins_there_are_in_all_without.mp3",
  "That is the magic of ARRAYS!": "/assets/audio/emphasis_that_is_the_magic_of_arrays.mp3",
  "When objects are arranged in equal rows and equal columns, we can MULTIPLY instead of count!": "/assets/audio/statement_when_objects_are_arranged_in_equal_rows_and_equal_columns_we.mp3",
  "Get ready to discover arrays!": "/assets/audio/celebration_get_ready_to_discover_arrays.mp3",
  "Welcome, young mathematician! I am LearnFlow, your learning companion.": "/assets/audio/statement_welcome_young_mathematician_i_am_learnflow_your_learning_com.mp3",
  "Imagine this... It is morning at school. The lunch lady is arranging muffins on a tray.": "/assets/audio/thinking_imagine_this_it_is_morning_at_school_the_lunch_lady_is_arran.mp3",
  "She places 3 rows of muffins, with 4 muffins in each row.": "/assets/audio/statement_she_places_3_rows_of_muffins_with_4_muffins_in_each_row.mp3",
  "Can you figure out how many muffins there are in all, without counting one by one?": "/assets/audio/question_can_you_figure_out_how_many_muffins_there_are_in_all_without.mp3",
  "That is the magic of arrays! Rows and columns help us multiply!": "/assets/audio/emphasis_that_is_the_magic_of_arrays_rows_and_columns_help_us_multipl.mp3",
  "Get ready to discover how arrays make multiplication easy and fun!": "/assets/audio/celebration_get_ready_to_discover_how_arrays_make_multiplication_easy_an.mp3",
  "Ryan is a second grade student at Maplewood Elementary School.": "/assets/audio/statement_ryan_is_a_second_grade_student_at_maplewood_elementary_schoo.mp3",
  "One morning, his teacher Ms. Parker asked for a volunteer to help set up the gym for the school assembly.": "/assets/audio/statement_one_morning_his_teacher_ms_parker_asked_for_a_volunteer_to_h.mp3",
  "Ms. Parker said: Ryan, please make 4 rows of chairs, with 5 chairs in each row.": "/assets/audio/statement_ms_parker_said_ryan_please_make_4_rows_of_chairs_with_5_chai.mp3",
  "Ryan started placing them one by one.": "/assets/audio/statement_ryan_started_placing_them_one_by_one.mp3",
  "When Ryan finished, he stepped back and saw the chairs formed a perfect rectangle.": "/assets/audio/statement_when_ryan_finished_he_stepped_back_and_saw_the_chairs_formed.mp3",
  "Rows going across, columns going down — an ARRAY!": "/assets/audio/emphasis_rows_going_across_columns_going_down_an_array.mp3",
  "Ms. Parker pointed at the board. Rows go ACROSS. Columns go DOWN.": "/assets/audio/statement_ms_parker_pointed_at_the_board_rows_go_across_columns_go_dow.mp3",
  "Your array has 4 rows and 5 columns!": "/assets/audio/emphasis_your_array_has_4_rows_and_5_columns.mp3",
  "Ms. Parker wrote on the whiteboard: 4 times 5 equals 20.": "/assets/audio/statement_ms_parker_wrote_on_the_whiteboard_4_times_5_equals_20.mp3",
  "This is a multiplication sentence! 4 rows of 5 equals 20 — no counting one by one!": "/assets/audio/celebration_this_is_a_multiplication_sentence_4_rows_of_5_equals_20_no_c.mp3",
  "Now YOU will build arrays, find missing numbers, and write multiplication sentences — just like Ryan.": "/assets/audio/celebration_now_you_will_build_arrays_find_missing_numbers_and_write_mul.mp3",
  "Rows times Columns equals Total. Let us go!": "/assets/audio/emphasis_rows_times_columns_equals_total_let_us_go.mp3",
  "Welcome to Station A — the Array Builder!": "/assets/audio/statement_welcome_to_station_a_the_array_builder.mp3",
  "Use the plus and minus buttons to add or remove rows and columns.": "/assets/audio/statement_use_the_plus_and_minus_buttons_to_add_or_remove_rows_and_col.mp3",
  "Watch the multiplication sentence update as you build your array!": "/assets/audio/emphasis_watch_the_multiplication_sentence_update_as_you_build_your_a.mp3",
  "Can you build an array with 3 rows and 4 columns? What is the total?": "/assets/audio/question_can_you_build_an_array_with_3_rows_and_4_columns_what_is_the.mp3",
  "Great work! Now try Station B — the Missing Factor Finder!": "/assets/audio/encouragement_great_work_now_try_station_b_the_missing_factor_finder.mp3",
  "I will show you an array, but one part is hidden with a question mark.": "/assets/audio/statement_i_will_show_you_an_array_but_one_part_is_hidden_with_a_quest.mp3",
  "Look at the array carefully. How many rows or columns are missing?": "/assets/audio/emphasis_look_at_the_array_carefully_how_many_rows_or_columns_are_mis.mp3",
  "Type your answer using the number pad and press Check to see if you are right!": "/assets/audio/statement_type_your_answer_using_the_number_pad_and_press_check_to_see.mp3",
  "Excellent! You have reached Station C — the Multiplication Sentence!": "/assets/audio/celebration_excellent_you_have_reached_station_c_the_multiplication_sent.mp3",
  "Here you will see a multiplication sentence with one blank to fill in.": "/assets/audio/statement_here_you_will_see_a_multiplication_sentence_with_one_blank_t.mp3",
  "Use what you know about rows and columns to find the missing number!": "/assets/audio/emphasis_use_what_you_know_about_rows_and_columns_to_find_the_missing.mp3",
  "If you need help, tap the hint button to see the array diagram!": "/assets/audio/statement_if_you_need_help_tap_the_hint_button_to_see_the_array_diagra.mp3",
  "Great job! You completed all three stations!": "/assets/audio/celebration_great_job_you_completed_all_three_stations.mp3",
  "You built arrays, found missing factors, and wrote multiplication sentences.": "/assets/audio/statement_you_built_arrays_found_missing_factors_and_wrote_multiplicat.mp3",
  "Now you are entering Test Mode. Answer all 100 questions to show what you know.": "/assets/audio/emphasis_now_you_are_entering_test_mode_answer_all_100_questions_to_s.mp3",
  "Good luck! You can do this!": "/assets/audio/statement_good_luck_you_can_do_this.mp3",
  "Amazing work today! You have completed the entire lesson on arrays!": "/assets/audio/celebration_amazing_work_today_you_have_completed_the_entire_lesson_on_a.mp3",
  "You learned that an array is a group of objects arranged in equal rows and columns.": "/assets/audio/statement_you_learned_that_an_array_is_a_group_of_objects_arranged_in_.mp3",
  "Rows go across. Columns go down. Rows times columns equals the total.": "/assets/audio/emphasis_rows_go_across_columns_go_down_rows_times_columns_equals_the.mp3",
  "You also discovered that multiplication is just a fast way to count equal groups!": "/assets/audio/statement_you_also_discovered_that_multiplication_is_just_a_fast_way_t.mp3",
  "Before we finish, take a moment to think about what you learned today.": "/assets/audio/question_before_we_finish_take_a_moment_to_think_about_what_you_learn.mp3",
  "Tell me one thing that surprised you, or one thing you found tricky. I am here to help!": "/assets/audio/encouragement_tell_me_one_thing_that_surprised_you_or_one_thing_you_found_.mp3",
  "Build an array with 3 rows and 4 columns.": "/assets/audio/question_build_an_array_with_3_rows_and_4_columns.mp3",
  "You need 3 rows and 4 columns. Use the plus and minus buttons to build it!": "/assets/audio/statement_you_need_3_rows_and_4_columns_use_the_plus_and_minus_buttons.mp3",
  "That is correct! 3 times 4 equals 12. Well done!": "/assets/audio/celebration_that_is_correct_3_times_4_equals_12_well_done.mp3",
  "Build an array with 2 rows and 5 columns.": "/assets/audio/question_build_an_array_with_2_rows_and_5_columns.mp3",
  "You need 2 rows and 5 columns. Use the plus and minus buttons to build it!": "/assets/audio/statement_you_need_2_rows_and_5_columns_use_the_plus_and_minus_buttons.mp3",
  "That is correct! 2 times 5 equals 10. Well done!": "/assets/audio/celebration_that_is_correct_2_times_5_equals_10_well_done.mp3",
  "Build an array with 4 rows and 3 columns.": "/assets/audio/question_build_an_array_with_4_rows_and_3_columns.mp3",
  "You need 4 rows and 3 columns. Use the plus and minus buttons to build it!": "/assets/audio/statement_you_need_4_rows_and_3_columns_use_the_plus_and_minus_buttons.mp3",
  "That is correct! 4 times 3 equals 12. Well done!": "/assets/audio/celebration_that_is_correct_4_times_3_equals_12_well_done.mp3"
};
export default audioMap;
