// Auto-generated — do not edit manually
// Run: node scripts/generate_audio.js
const audioMap = {
  "Welcome, young mathematician! I am LearnFlow, your learning companion.": "/assets/audio/statement_welcome_young_mathematician_i_am_learnflow_your_learning_com.mp3",
  "Imagine this... It is morning at school. The canteen aunty is arranging muffins on a tray.": "/assets/audio/thinking_imagine_this_it_is_morning_at_school_the_canteen_aunty_is_ar.mp3",
  "She places 3 rows of muffins, with 4 muffins in each row.": "/assets/audio/statement_she_places_3_rows_of_muffins_with_4_muffins_in_each_row.mp3",
  "Can you figure out how many muffins there are in all, without counting one by one?": "/assets/audio/question_can_you_figure_out_how_many_muffins_there_are_in_all_without.mp3",
  "That is the magic of arrays! Rows and columns help us multiply!": "/assets/audio/emphasis_that_is_the_magic_of_arrays_rows_and_columns_help_us_multipl.mp3",
  "Get ready to discover how arrays make multiplication easy and fun!": "/assets/audio/celebration_get_ready_to_discover_how_arrays_make_multiplication_easy_an.mp3",
  "Let me tell you about Ryan. Ryan is a Primary 2 student at Westwood Primary School.": "/assets/audio/statement_let_me_tell_you_about_ryan_ryan_is_a_primary_2_student_at_we.mp3",
  "One day, his teacher asked him to help set up chairs in the hall for an assembly.": "/assets/audio/statement_one_day_his_teacher_asked_him_to_help_set_up_chairs_in_the_h.mp3",
  "Ryan placed 4 rows of chairs, with 5 chairs in each row.": "/assets/audio/statement_ryan_placed_4_rows_of_chairs_with_5_chairs_in_each_row.mp3",
  "Ryan wondered: how many chairs did he set up in all?": "/assets/audio/question_ryan_wondered_how_many_chairs_did_he_set_up_in_all.mp3",
  "Ryan looked carefully. He saw 4 rows, each with 5 chairs.": "/assets/audio/emphasis_ryan_looked_carefully_he_saw_4_rows_each_with_5_chairs.mp3",
  "He wrote it as a multiplication sentence: 4 times 5 equals 20.": "/assets/audio/statement_he_wrote_it_as_a_multiplication_sentence_4_times_5_equals_20.mp3",
  "The chairs were arranged in an array! An array has equal rows and equal columns.": "/assets/audio/statement_the_chairs_were_arranged_in_an_array_an_array_has_equal_rows.mp3",
  "Rows go across. Columns go up and down. And rows times columns gives us the total!": "/assets/audio/emphasis_rows_go_across_columns_go_up_and_down_and_rows_times_columns.mp3",
  "Ryan counted: 5, 10, 15, 20. Yes! 20 chairs in all. Ryan did it!": "/assets/audio/celebration_ryan_counted_5_10_15_20_yes_20_chairs_in_all_ryan_did_it.mp3",
  "Now YOU will learn to read and build arrays just like Ryan!": "/assets/audio/encouragement_now_you_will_learn_to_read_and_build_arrays_just_like_ryan.mp3",
  "Welcome to Station A — the Array Builder!": "/assets/audio/statement_welcome_to_station_a_the_array_builder.mp3",
  "Use the plus and minus buttons to add or remove rows and columns.": "/assets/audio/statement_use_the_plus_and_minus_buttons_to_add_or_remove_rows_and_col.mp3",
  "Watch the multiplication sentence update as you build your array!": "/assets/audio/emphasis_watch_the_multiplication_sentence_update_as_you_build_your_a.mp3",
  "Can you build an array with 3 rows and 4 columns? What is the total?": "/assets/audio/question_can_you_build_an_array_with_3_rows_and_4_columns_what_is_the.mp3",
  "Great work! Now try Station B — the Missing Factor Finder!": "/assets/audio/encouragement_great_work_now_try_station_b_the_missing_factor_finder.mp3",
  "I will show you an array, but one part is hidden with a question mark.": "/assets/audio/statement_i_will_show_you_an_array_but_one_part_is_hidden_with_a_quest.mp3",
  "Look at the array carefully. How many rows or columns are missing?": "/assets/audio/emphasis_look_at_the_array_carefully_how_many_rows_or_columns_are_mis.mp3",
  "Type your answer using the number pad and press Check to see if you are right!": "/assets/audio/statement_type_your_answer_using_the_number_pad_and_press_check_to_see.mp3",
  "Excellent! You have reached Station C — the Multiplication Sentence!": "/assets/audio/celebration_excellent_you_have_reached_station_c_the_multiplication_sent.mp3",
  "Here you will see a multiplication sentence with one blank to fill in.": "/assets/audio/statement_here_you_will_see_a_multiplication_sentence_with_one_blank_t.mp3",
  "Use what you know about rows and columns to find the missing number!": "/assets/audio/emphasis_use_what_you_know_about_rows_and_columns_to_find_the_missing.mp3",
  "If you need help, tap the hint button to see the array diagram!": "/assets/audio/statement_if_you_need_help_tap_the_hint_button_to_see_the_array_diagra.mp3",
  "Amazing work today! You have completed the entire lesson on arrays!": "/assets/audio/celebration_amazing_work_today_you_have_completed_the_entire_lesson_on_a.mp3",
  "You learned that an array is a group of objects arranged in equal rows and columns.": "/assets/audio/statement_you_learned_that_an_array_is_a_group_of_objects_arranged_in_.mp3",
  "Rows go across. Columns go down. Rows times columns equals the total.": "/assets/audio/emphasis_rows_go_across_columns_go_down_rows_times_columns_equals_the.mp3",
  "You also discovered that multiplication is just a fast way to count equal groups!": "/assets/audio/statement_you_also_discovered_that_multiplication_is_just_a_fast_way_t.mp3",
  "Before we finish, take a moment to think about what you learned today.": "/assets/audio/question_before_we_finish_take_a_moment_to_think_about_what_you_learn.mp3",
  "Tell me one thing that surprised you, or one thing you found tricky. I am here to help!": "/assets/audio/encouragement_tell_me_one_thing_that_surprised_you_or_one_thing_you_found_.mp3",
  "Look at the array. How many tiles are there in all? What is 3 times 4?": "/assets/audio/question_look_at_the_array_how_many_tiles_are_there_in_all_what_is_3_.mp3",
  "Look at the array. How many stars are there in all? What is 2 times 5?": "/assets/audio/question_look_at_the_array_how_many_stars_are_there_in_all_what_is_2_.mp3",
  "Look at the array. How many dots are there in all? What is 4 times 3?": "/assets/audio/question_look_at_the_array_how_many_dots_are_there_in_all_what_is_4_t.mp3",
  "Look at the array. How many circles are there in all? What is 5 times 2?": "/assets/audio/question_look_at_the_array_how_many_circles_are_there_in_all_what_is_.mp3",
  "Look at the array. How many squares are there in all? What is 3 times 3?": "/assets/audio/question_look_at_the_array_how_many_squares_are_there_in_all_what_is_.mp3",
  "Look at the array. How many tiles are there in all? What is 4 times 5?": "/assets/audio/question_look_at_the_array_how_many_tiles_are_there_in_all_what_is_4_.mp3",
  "Look at the array. How many dots are there in all? What is 3 times 6?": "/assets/audio/question_look_at_the_array_how_many_dots_are_there_in_all_what_is_3_t.mp3",
  "Look at the array. How many shapes are there in all? What is 5 times 4?": "/assets/audio/question_look_at_the_array_how_many_shapes_are_there_in_all_what_is_5.mp3",
  "Look at the array. How many tiles are there in all? What is 7 times 6?": "/assets/audio/question_look_at_the_array_how_many_tiles_are_there_in_all_what_is_7_.mp3",
  "Look at the array. How many dots are there in all? What is 8 times 9?": "/assets/audio/question_look_at_the_array_how_many_dots_are_there_in_all_what_is_8_t.mp3",
  "2 times 3 equals blank": "/assets/audio/question_2_times_3_equals_blank.mp3",
  "5 times 2 equals blank": "/assets/audio/question_5_times_2_equals_blank.mp3",
  "3 times 5 equals blank": "/assets/audio/question_3_times_5_equals_blank.mp3",
  "4 times 4 equals blank": "/assets/audio/question_4_times_4_equals_blank.mp3",
  "5 times blank equals 15": "/assets/audio/question_5_times_blank_equals_15.mp3",
  "3 times 7 equals blank": "/assets/audio/question_3_times_7_equals_blank.mp3",
  "blank times 6 equals 24": "/assets/audio/question_blank_times_6_equals_24.mp3",
  "6 times 5 equals blank": "/assets/audio/question_6_times_5_equals_blank.mp3",
  "8 times 7 equals blank": "/assets/audio/question_8_times_7_equals_blank.mp3",
  "9 times 6 equals blank": "/assets/audio/question_9_times_6_equals_blank.mp3",
  "Look at the picture. Write the multiplication sentence for this array. What is 2 times 4?": "/assets/audio/question_look_at_the_picture_write_the_multiplication_sentence_for_th.mp3",
  "Look at the picture. How many items are in this array? What is 3 times 3?": "/assets/audio/question_look_at_the_picture_how_many_items_are_in_this_array_what_is.mp3",
  "Look at the picture. Write the multiplication for this array. What is 4 times 2?": "/assets/audio/question_look_at_the_picture_write_the_multiplication_for_this_array_.mp3",
  "Look at the picture. What multiplication sentence matches? What is 5 times 3?": "/assets/audio/question_look_at_the_picture_what_multiplication_sentence_matches_wha.mp3",
  "Look at the picture. How many objects are there in all? What is 2 times 5?": "/assets/audio/question_look_at_the_picture_how_many_objects_are_there_in_all_what_i.mp3",
  "Look at the picture. How many tiles are in this array? What is 4 times 6?": "/assets/audio/question_look_at_the_picture_how_many_tiles_are_in_this_array_what_is.mp3",
  "Look at the picture. What is the total count? What is 3 times 8?": "/assets/audio/question_look_at_the_picture_what_is_the_total_count_what_is_3_times_.mp3",
  "Look at the picture. How many items are in this array? What is 5 times 7?": "/assets/audio/question_look_at_the_picture_how_many_items_are_in_this_array_what_is.mp3",
  "Look at the picture. How many dots are in this array? What is 7 times 8?": "/assets/audio/question_look_at_the_picture_how_many_dots_are_in_this_array_what_is_.mp3",
  "Look at the picture. What is the total number of tiles? What is 9 times 7?": "/assets/audio/question_look_at_the_picture_what_is_the_total_number_of_tiles_what_i.mp3",
  "Ethan arranges 3 rows of erasers, with 4 erasers in each row. How many erasers are there in all? What is 3 times 4?": "/assets/audio/question_ethan_arranges_3_rows_of_erasers_with_4_erasers_in_each_row_.mp3",
  "Emma places 5 rows of stickers, with 3 stickers in each row. How many stickers are there in all? What is 5 times 3?": "/assets/audio/question_emma_places_5_rows_of_stickers_with_3_stickers_in_each_row_h.mp3",
  "Mia arranges 4 rows of muffins, with 5 muffins in each row. How many muffins are there in all? What is 4 times 5?": "/assets/audio/question_mia_arranges_4_rows_of_muffins_with_5_muffins_in_each_row_ho.mp3",
  "Noah puts 2 rows of books on a shelf, with 6 books in each row. How many books are there in all? What is 2 times 6?": "/assets/audio/question_noah_puts_2_rows_of_books_on_a_shelf_with_6_books_in_each_ro.mp3",
  "Olivia plants 3 rows of flowers, with 7 flowers in each row. How many flowers are there in all? What is 3 times 7?": "/assets/audio/question_olivia_plants_3_rows_of_flowers_with_7_flowers_in_each_row_h.mp3",
  "Liam arranges 4 rows of tiles, with 8 tiles in each row. How many tiles are there in all? What is 4 times 8?": "/assets/audio/question_liam_arranges_4_rows_of_tiles_with_8_tiles_in_each_row_how_m.mp3",
  "Lucas sets up 6 rows of chairs, with 7 chairs in each row. How many chairs are there in all? What is 6 times 7?": "/assets/audio/question_lucas_sets_up_6_rows_of_chairs_with_7_chairs_in_each_row_how.mp3",
  "Sophia places 7 rows of stickers, with 5 stickers in each row. How many stickers are there in all? What is 7 times 5?": "/assets/audio/question_sophia_places_7_rows_of_stickers_with_5_stickers_in_each_row.mp3",
  "Ryan arranges 8 rows of muffins, with 6 muffins in each row. How many muffins are there in all? What is 8 times 6?": "/assets/audio/question_ryan_arranges_8_rows_of_muffins_with_6_muffins_in_each_row_h.mp3",
  "Emma arranges 9 rows of tiles, with 8 tiles in each row. How many tiles are there in all? What is 9 times 8?": "/assets/audio/question_emma_arranges_9_rows_of_tiles_with_8_tiles_in_each_row_how_m.mp3",
  "4 + 4 + 4 equals blank. Write this as a multiplication sentence.": "/assets/audio/question_4_4_4_equals_blank_write_this_as_a_multiplication_sentence.mp3",
  "5 + 5 equals blank. Write this as a multiplication sentence.": "/assets/audio/question_5_5_equals_blank_write_this_as_a_multiplication_sentence.mp3",
  "3 + 3 + 3 + 3 equals blank. Write as multiplication.": "/assets/audio/question_3_3_3_3_equals_blank_write_as_multiplication.mp3",
  "2 + 2 + 2 + 2 + 2 equals blank. Write as multiplication.": "/assets/audio/question_2_2_2_2_2_equals_blank_write_as_multiplication.mp3",
  "6 + 6 + 6 equals blank. Write as multiplication.": "/assets/audio/question_6_6_6_equals_blank_write_as_multiplication.mp3",
  "7 + 7 + 7 + 7 equals blank. Write as multiplication.": "/assets/audio/question_7_7_7_7_equals_blank_write_as_multiplication.mp3",
  "8 + 8 + 8 + 8 + 8 equals blank. Write as multiplication.": "/assets/audio/question_8_8_8_8_8_equals_blank_write_as_multiplication.mp3",
  "9 + 9 + 9 + 9 + 9 + 9 equals blank. Write as multiplication.": "/assets/audio/question_9_9_9_9_9_9_equals_blank_write_as_multiplication.mp3",
  "8 + 8 + 8 + 8 + 8 + 8 + 8 equals blank. Write as multiplication.": "/assets/audio/question_8_8_8_8_8_8_8_equals_blank_write_as_multiplication.mp3",
  "9 + 9 + 9 + 9 + 9 + 9 + 9 + 9 + 9 equals blank. Write as multiplication.": "/assets/audio/question_9_9_9_9_9_9_9_9_9_equals_blank_write_as_multiplication.mp3",
  "Is this correct? 3 times 4 equals 12": "/assets/audio/question_is_this_correct_3_times_4_equals_12.mp3",
  "Is this correct? 2 times 5 equals 12": "/assets/audio/question_is_this_correct_2_times_5_equals_12.mp3",
  "Is this correct? 4 times 3 equals 14": "/assets/audio/question_is_this_correct_4_times_3_equals_14.mp3",
  "Is this correct? 5 times 2 equals 10": "/assets/audio/question_is_this_correct_5_times_2_equals_10.mp3",
  "Is this correct? 3 times 3 equals 9": "/assets/audio/question_is_this_correct_3_times_3_equals_9.mp3",
  "Is this correct? 4 times 5 equals 18": "/assets/audio/question_is_this_correct_4_times_5_equals_18.mp3",
  "Is this correct? 6 times 4 equals 24": "/assets/audio/question_is_this_correct_6_times_4_equals_24.mp3",
  "Is this correct? 7 times 3 equals 24": "/assets/audio/question_is_this_correct_7_times_3_equals_24.mp3",
  "Is this correct? 8 times 8 equals 64": "/assets/audio/question_is_this_correct_8_times_8_equals_64.mp3",
  "Is this correct? 9 times 7 equals 56": "/assets/audio/question_is_this_correct_9_times_7_equals_56.mp3",
  "Which array matches 2 times 4 equals 8?": "/assets/audio/question_which_array_matches_2_times_4_equals_8.mp3",
  "Which array matches 3 times 5 equals 15?": "/assets/audio/question_which_array_matches_3_times_5_equals_15.mp3",
  "Which array matches 4 times 4 equals 16?": "/assets/audio/question_which_array_matches_4_times_4_equals_16.mp3",
  "Which array matches 5 times 3 equals 15?": "/assets/audio/question_which_array_matches_5_times_3_equals_15.mp3",
  "Which array matches 3 times 6 equals 18?": "/assets/audio/question_which_array_matches_3_times_6_equals_18.mp3",
  "Which array matches 2 times 9 equals 18?": "/assets/audio/question_which_array_matches_2_times_9_equals_18.mp3",
  "Which array matches 4 times 7 equals 28?": "/assets/audio/question_which_array_matches_4_times_7_equals_28.mp3",
  "Which array matches 6 times 8 equals 48?": "/assets/audio/question_which_array_matches_6_times_8_equals_48.mp3",
  "Which array matches 7 times 9 equals 63?": "/assets/audio/question_which_array_matches_7_times_9_equals_63.mp3",
  "Which array matches 8 times 10 equals 80?": "/assets/audio/question_which_array_matches_8_times_10_equals_80.mp3",
  "An array has 3 rows. Each row has 4 objects. Write the multiplication sentence. What is 3 times 4?": "/assets/audio/question_an_array_has_3_rows_each_row_has_4_objects_write_the_multipl.mp3",
  "An array has 2 rows. Each row has 5 objects. What is the total? What is 2 times 5?": "/assets/audio/question_an_array_has_2_rows_each_row_has_5_objects_what_is_the_total.mp3",
  "An array has 4 rows with 3 objects in each row. What is the total? What is 4 times 3?": "/assets/audio/question_an_array_has_4_rows_with_3_objects_in_each_row_what_is_the_t.mp3",
  "An array has blank rows with 3 in each row, and 18 objects in all. How many rows are there? What number times 3 equals 18?": "/assets/audio/question_an_array_has_blank_rows_with_3_in_each_row_and_18_objects_in.mp3",
  "An array has 5 rows. Each row has 4 objects. What is the total? What is 5 times 4?": "/assets/audio/question_an_array_has_5_rows_each_row_has_4_objects_what_is_the_total.mp3",
  "An array has 7 rows and 28 objects in all. How many objects are in each row? 7 times what number equals 28?": "/assets/audio/question_an_array_has_7_rows_and_28_objects_in_all_how_many_objects_a.mp3",
  "An array has 8 rows. Each row has 5 objects. What is the total? What is 8 times 5?": "/assets/audio/question_an_array_has_8_rows_each_row_has_5_objects_what_is_the_total.mp3",
  "An array has 9 rows with 6 objects in each row. What is the total? What is 9 times 6?": "/assets/audio/question_an_array_has_9_rows_with_6_objects_in_each_row_what_is_the_t.mp3",
  "An array has 10 rows. Each row has 7 objects. What is the total? What is 10 times 7?": "/assets/audio/question_an_array_has_10_rows_each_row_has_7_objects_what_is_the_tota.mp3",
  "An array has 8 rows and 72 objects in all. How many objects are in each row? 8 times what number equals 72?": "/assets/audio/question_an_array_has_8_rows_and_72_objects_in_all_how_many_objects_a.mp3",
  "6 rows times 6 columns equals blank": "/assets/audio/question_6_rows_times_6_columns_equals_blank.mp3",
  "7 rows times 5 columns equals blank": "/assets/audio/question_7_rows_times_5_columns_equals_blank.mp3",
  "8 rows times 6 columns equals blank": "/assets/audio/question_8_rows_times_6_columns_equals_blank.mp3",
  "9 rows times 5 columns equals blank": "/assets/audio/question_9_rows_times_5_columns_equals_blank.mp3",
  "7 rows times 7 columns equals blank": "/assets/audio/question_7_rows_times_7_columns_equals_blank.mp3",
  "6 rows times 9 columns equals blank": "/assets/audio/question_6_rows_times_9_columns_equals_blank.mp3",
  "8 rows times 7 columns equals blank": "/assets/audio/question_8_rows_times_7_columns_equals_blank.mp3",
  "9 rows times 8 columns equals blank": "/assets/audio/question_9_rows_times_8_columns_equals_blank.mp3",
  "10 rows times 9 columns equals blank": "/assets/audio/question_10_rows_times_9_columns_equals_blank.mp3",
  "10 rows times 10 columns equals blank": "/assets/audio/question_10_rows_times_10_columns_equals_blank.mp3",
  "3 times blank equals 12. What is the missing number?": "/assets/audio/question_3_times_blank_equals_12_what_is_the_missing_number.mp3",
  "blank times 2 equals 10. What is the missing number?": "/assets/audio/question_blank_times_2_equals_10_what_is_the_missing_number.mp3",
  "4 times blank equals 20. What is the missing number?": "/assets/audio/question_4_times_blank_equals_20_what_is_the_missing_number.mp3",
  "blank times 6 equals 12. What is the missing number?": "/assets/audio/question_blank_times_6_equals_12_what_is_the_missing_number.mp3",
  "3 times blank equals 21. What is the missing number?": "/assets/audio/question_3_times_blank_equals_21_what_is_the_missing_number.mp3",
  "blank times 4 equals 24. What is the missing number?": "/assets/audio/question_blank_times_4_equals_24_what_is_the_missing_number.mp3",
  "5 times blank equals 40. What is the missing number?": "/assets/audio/question_5_times_blank_equals_40_what_is_the_missing_number.mp3",
  "blank times 6 equals 42. What is the missing number?": "/assets/audio/question_blank_times_6_equals_42_what_is_the_missing_number.mp3",
  "8 times blank equals 72. What is the missing number?": "/assets/audio/question_8_times_blank_equals_72_what_is_the_missing_number.mp3",
  "blank times 7 equals 63. What is the missing number?": "/assets/audio/question_blank_times_7_equals_63_what_is_the_missing_number.mp3"
};
export default audioMap;
