// Auto-generated — do not edit manually
// Run: node scripts/generate_audio.js
const audioMap = {
  "Welcome, young mathematician! I am LearnFlow, your learning companion.": "/assets/audio/statement_welcome_young_mathematician_i_am_learnflow_your_learning_com.mp3",
  "Imagine this... It is morning at school. The canteen aunty is arranging muffins on a tray.": "/assets/audio/thinking_imagine_this_it_is_morning_at_school_the_canteen_aunty_is_ar.mp3",
  "She places 3 rows of muffins, with 4 muffins in each row.": "/assets/audio/statement_she_places_3_rows_of_muffins_with_4_muffins_in_each_row.mp3",
  "Can you figure out how many muffins there are in all, without counting one by one?": "/assets/audio/question_can_you_figure_out_how_many_muffins_there_are_in_all_without.mp3",
  "That is the magic of arrays! Rows and columns help us multiply!": "/assets/audio/emphasis_that_is_the_magic_of_arrays_rows_and_columns_help_us_multipl.mp3",
  "Get ready to discover how arrays make multiplication easy and fun!": "/assets/audio/celebration_get_ready_to_discover_how_arrays_make_multiplication_easy_an.mp3",
  "Let me tell you about Ryan. Ryan is a Primary 2 student at Westwood Primary School.": "/assets/audio/statement_let_me_tell_you_about_ryan_ryan_is_a_primary_2_student_at_we.mp3",
  "One day, his teacher asked him to help set up chairs in the hall for an assembly.": "/assets/audio/statement_one_day_his_teacher_asked_him_to_help_set_up_chairs_in_the_h.mp3",
  "Ryan placed 4 rows of chairs, with 5 chairs in each row.": "/assets/audio/statement_ryan_placed_4_rows_of_chairs_with_5_chairs_in_each_row.mp3",
  "Ryan wondered: how many chairs did he set up in all?": "/assets/audio/question_ryan_wondered_how_many_chairs_did_he_set_up_in_all.mp3",
  "Ryan looked carefully. He saw 4 rows, each with 5 chairs.": "/assets/audio/emphasis_ryan_looked_carefully_he_saw_4_rows_each_with_5_chairs.mp3",
  "He wrote it as a multiplication sentence: 4 times 5 equals 20.": "/assets/audio/statement_he_wrote_it_as_a_multiplication_sentence_4_times_5_equals_20.mp3",
  "The chairs were arranged in an array! An array has equal rows and equal columns.": "/assets/audio/statement_the_chairs_were_arranged_in_an_array_an_array_has_equal_rows.mp3",
  "Rows go across. Columns go up and down. And rows times columns gives us the total!": "/assets/audio/emphasis_rows_go_across_columns_go_up_and_down_and_rows_times_columns.mp3",
  "Ryan counted: 5, 10, 15, 20. Yes! 20 chairs in all. Ryan did it!": "/assets/audio/celebration_ryan_counted_5_10_15_20_yes_20_chairs_in_all_ryan_did_it.mp3",
  "Now YOU will learn to read and build arrays just like Ryan!": "/assets/audio/encouragement_now_you_will_learn_to_read_and_build_arrays_just_like_ryan.mp3",
  "Welcome to Station A — the Array Builder!": "/assets/audio/statement_welcome_to_station_a_the_array_builder.mp3",
  "Use the plus and minus buttons to add or remove rows and columns.": "/assets/audio/statement_use_the_plus_and_minus_buttons_to_add_or_remove_rows_and_col.mp3",
  "Watch the multiplication sentence update as you build your array!": "/assets/audio/emphasis_watch_the_multiplication_sentence_update_as_you_build_your_a.mp3",
  "Can you build an array with 3 rows and 4 columns? What is the total?": "/assets/audio/question_can_you_build_an_array_with_3_rows_and_4_columns_what_is_the.mp3",
  "Great work! Now try Station B — the Missing Factor Finder!": "/assets/audio/encouragement_great_work_now_try_station_b_the_missing_factor_finder.mp3",
  "I will show you an array, but one part is hidden with a question mark.": "/assets/audio/statement_i_will_show_you_an_array_but_one_part_is_hidden_with_a_quest.mp3",
  "Look at the array carefully. How many rows or columns are missing?": "/assets/audio/emphasis_look_at_the_array_carefully_how_many_rows_or_columns_are_mis.mp3",
  "Type your answer using the number pad and press Check to see if you are right!": "/assets/audio/statement_type_your_answer_using_the_number_pad_and_press_check_to_see.mp3",
  "Excellent! You have reached Station C — the Multiplication Sentence!": "/assets/audio/celebration_excellent_you_have_reached_station_c_the_multiplication_sent.mp3",
  "Here you will see a multiplication sentence with one blank to fill in.": "/assets/audio/statement_here_you_will_see_a_multiplication_sentence_with_one_blank_t.mp3",
  "Use what you know about rows and columns to find the missing number!": "/assets/audio/emphasis_use_what_you_know_about_rows_and_columns_to_find_the_missing.mp3",
  "If you need help, tap the hint button to see the array diagram!": "/assets/audio/statement_if_you_need_help_tap_the_hint_button_to_see_the_array_diagra.mp3",
  "Amazing work today! You have completed the entire lesson on arrays!": "/assets/audio/celebration_amazing_work_today_you_have_completed_the_entire_lesson_on_a.mp3",
  "You learned that an array is a group of objects arranged in equal rows and columns.": "/assets/audio/statement_you_learned_that_an_array_is_a_group_of_objects_arranged_in_.mp3",
  "Rows go across. Columns go down. Rows times columns equals the total.": "/assets/audio/emphasis_rows_go_across_columns_go_down_rows_times_columns_equals_the.mp3",
  "You also discovered that multiplication is just a fast way to count equal groups!": "/assets/audio/statement_you_also_discovered_that_multiplication_is_just_a_fast_way_t.mp3",
  "Before we finish, take a moment to think about what you learned today.": "/assets/audio/question_before_we_finish_take_a_moment_to_think_about_what_you_learn.mp3",
  "Tell me one thing that surprised you, or one thing you found tricky. I am here to help!": "/assets/audio/encouragement_tell_me_one_thing_that_surprised_you_or_one_thing_you_found_.mp3"
};
export default audioMap;
